services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: scpms_user
      DB_PASSWORD: scpms_pass
      DB_NAME: scpms_db
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: scpms_user
      POSTGRES_PASSWORD: scpms_pass
      POSTGRES_DB: scpms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: